config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#index'
  
  get 'about' => 'static#about'
  get 'contact' => 'static#contact'
  
  get 'posts_index' => 'posts#index'
  get 'posts' => 'posts#new'
  post 'posts' => 'posts#create'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 10 }
  validates :body, presence: true, length: { minimum: 10 }
  validates :user_id, presence: true
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :generate_remember_token

  validates :username, presence: true, length: { in: 4..25 }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  has_many :posts
  
  def self.digest (string)
    Digest::SHA1.hexdigest(string)
  end
  
  private
  
    def generate_remember_token
      token = SecureRandom.urlsafe_base64
      token_digest = Digest::SHA1.hexdigest(token)
      self.remember_token = token_digest
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:new, :create]
  
  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = @current_user.id
    if @post.save
      flash[:success] = "New post has been successfully created."
      redirect_to posts_index_path
    else
      flash.now[:error] = "Couldn't create new post."
      render 'new'
    end
  end
  
  private
  
    def require_login
      unless logged_in?
        flash[:error] = "Please log in."
        redirect_to login_path
      end
    end
    
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      flash[:success] = "You've successfully logged in."
      redirect_to posts_index_path
    else
      flash.now[:error] = "Invalid email and/or password."
      render 'new'
    end
  end
  
  def destroy
    log_out if !current_user.nil?
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def log_in (user)
    fresh_token = SecureRandom.urlsafe_base64
    token_digest = User.digest(fresh_token)
    user.update_attribute(:remember_token, token_digest)
    cookies.permanent[:remember_token] = fresh_token
    current_user
  end
  
  def log_out
    cookies.delete(:remember_token)
    @current_user = nil
    flash[:success] = "You've successfully logged out."
    redirect_to login_path
  end
  
  def current_user
    return nil if cookies[:remember_token].nil?
    @current_user ||= User.find_by(remember_token: User.digest(cookies[:remember_token]))
  end
  
  def logged_in?
    current_user
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_header.html.erb
<div class="header">
  <div class="logo">
    <% if current_user.nil? %>
      <%= link_to image_tag("logo.png", alt: "Secret Club logo"), login_path %>
    <% else %>
      <%= link_to image_tag("logo.png", alt: "Secret Club logo"), posts_index_path %>
    <% end %>
  </div>
  <div class="nav">
    <%= link_to "Posts", posts_index_path %>
    <%= link_to "About", about_path %>
    <%= link_to "Contact us", contact_path %>
    <% if cookies[:remember_token].nil? %>
      <%= link_to "Log in", login_path, class: "nav-content" %><br/>
    <% else %>
      <%= link_to "Log out", logout_path, method: :delete %>
    <% end %>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim"  %>
</head>
<body>
<%= render "layouts/header" %>
<% flash.each do |msg_type, msg| %>
  <div class="message-container">
    <div class="message-<%= msg_type %>">
      <p class="message-body">
        <%= msg %>
      </p>
    </div>
  </div>
<% end %>
<%= yield %>
</body>
</html>

app/views/posts/index.html.erb
<h1>All posts</h1>
<div class="row">
  <div class="col-main">
    <% @posts.each do |p| %>
      <h2 class="post_title"><%= p.title %></h2>
      <p class="post_body"><%= p.body %></p>
      <p class="post_author">
        Written by: 
      <% if current_user %>
        <%= p.user.username %></p>
      <% else %>
        <span class="login-info"><i>hidden, please log in</i></span>
      <% end %>
    <% end %>
    <%= link_to "New post", posts_path %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<div class="row">
  <div class="col-main">
    <%= form_for @post do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
      
      <%= f.label :body, "New post" %>
      <%= f.text_area :body, class: "form-control" %>
    
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>